### ISSUE TITLE
关于测试的视频

### ISSUE THREAD

**Issue by lz233-alt** [yxuhan/CoRA#2]
抱歉，我并没有找到所说的测试视频用例，能否给一个有效的网址或链接以测试。

**Comment by yxuhan** [comment]
链接在这里  https://github.com/yxuhan/CoRA/blob/main/docs/Run.md

`# download a dataset from https://cloud.tsinghua.edu.cn/d/0d9bef2214dd42dc95d7/, e.g. old_neutral.zip`
