### ISSUE TITLE
模型权重问题

### ISSUE THREAD

**Issue by yangyang117** [yxuhan/CoRA#3]
你好，请问训练好的权重开放出来了吗？我看run.md只有训练的代码和说明。权重后期会开放吗？

**Comment by YiChenCityU** [comment]
每个人都是重新训练的，没有预训练的模型

**Comment by yxuhan** [comment]
@yangyang117  old_neutral的checkpoint在这里可以下载：https://cloud.tsinghua.edu.cn/f/074d56b606614eb68ab4/
