### ISSUE TITLE
About metashape

### ISSUE THREAD

**Issue by lz233-alt** [yxuhan/CoRA#4]
Hello, I tested the data preprocessing method as soon as you opened it up. Unfortunately, due to my lack of knowledge about Metapaper, I was unable to obtain an effective OBJ. Could you please release a Metapaper tutorial as soon as possible so that I can conduct my own testing on this amazing job

**Comment by Karlie-Luo** [comment]
Need a metashape tutorial too!Thanks!

**Comment by yxuhan** [comment]
Hi @lz233-alt and @Karlie-Luo , I will add the tutorial for metashape very soon.

**Comment by yxuhan** [comment]
Done. @Karlie-Luo @lz233-alt see docs/Preprocess.md.
