### ISSUE TITLE
如何获取手机手电筒的参数

### ISSUE THREAD

**Issue by ZJNC-CJP** [yxuhan/CoRA#5]
作者您好，请问我要从何获取手电的相关参数（intensity、color和gamma），我自己1+ACE2拍摄的图片在最后运行run.md里的命令会失败，估计是没改手电参数的原因。

**Comment by yxuhan** [comment]
hi  具体哪条命令会失败？一般手机的gamma都是2.2，不需要改变。intensity会影响求解出的reflectance map的整体尺度，在我们的方法里intensity没有物理单位，可以尝试下改小变成6或者改大变成12。对大部分手机来说，color设置成[1,1,1]就可以了，代表手机闪光灯的颜色。代码出错也有可能是图像分辨率的问题，因为我在代码里把分辨率硬编码成960x720了，可以在相应位置改下代码为实际的图像分辨率：
https://github.com/yxuhan/CoRA/blob/07870738cd16c81a4f904ea191ef14b21c2da10e/scripts/AlbedoMMFitting/fitting.py#L90

**Comment by yxuhan** [comment]
Finished as no further reply.
