### ISSUE TITLE
diffuse贴图颜色感觉不太对

### ISSUE THREAD

**Issue by alphazhugit** [yxuhan/CoRA#6]
使用提供视频“old_neutral.MOV”，最终算出来的贴图，diffusemap颜色就跟文档Run.md里出来的一样，是偏红色的，感觉不太对，不知道哪里出了问题。
另外，normalmap是否可以算出切线空间的法线贴图现在算出来的应该是世界空间的吧

**Comment by Karlie-Luo** [comment]
你好！请问你有复刻作者提到的使用metashape进行camera calibrate操作吗？如果有的话是否可以指点一下我如何进行这一步？非常感谢！

**Comment by yxuhan** [comment]
> 使用提供视频“old_neutral.MOV”，最终算出来的贴图，diffusemap颜色就跟文档Run.md里出来的一样，是偏红色的，感觉不太对，不知道哪里出了问题。 另外，normalmap是否可以算出切线空间的法线贴图现在算出来的应该是世界空间的吧

diffuse map的颜色空间是linear space，对他开2.2次方后就可以得到srgb空间的图像，i.e. diffuse map ** (1/2.2)     normal map是在object space，可以在blender中bake到tangent space

**Comment by alphazhugit** [comment]
> 你好！请问你有复刻作者提到的使用metashape进行camera calibrate操作吗？如果有的话是否可以指点一下我如何进行这一步？非常感谢！

菜单栏，工作流程，对齐照片，生成网格，然后导出那边，导出相机就能得到作者提到的数据
